// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fatcatfablab/fcfl-member-sync/stripe/listener (interfaces: memberDb,uaUpdater)
//
// Generated by this command:
//
//	mockgen --destination mock_listener_test.go --package listener . memberDb,uaUpdater
//

// Package listener is a generated GoMock package.
package listener

import (
	reflect "reflect"

	types "github.com/fatcatfablab/fcfl-member-sync/stripe/types"
	types0 "github.com/fatcatfablab/fcfl-member-sync/types"
	gomock "go.uber.org/mock/gomock"
)

// MockmemberDb is a mock of memberDb interface.
type MockmemberDb struct {
	ctrl     *gomock.Controller
	recorder *MockmemberDbMockRecorder
	isgomock struct{}
}

// MockmemberDbMockRecorder is the mock recorder for MockmemberDb.
type MockmemberDbMockRecorder struct {
	mock *MockmemberDb
}

// NewMockmemberDb creates a new mock instance.
func NewMockmemberDb(ctrl *gomock.Controller) *MockmemberDb {
	mock := &MockmemberDb{ctrl: ctrl}
	mock.recorder = &MockmemberDbMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmemberDb) EXPECT() *MockmemberDbMockRecorder {
	return m.recorder
}

// ActivateMember mocks base method.
func (m *MockmemberDb) ActivateMember(customerId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateMember", customerId)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateMember indicates an expected call of ActivateMember.
func (mr *MockmemberDbMockRecorder) ActivateMember(customerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateMember", reflect.TypeOf((*MockmemberDb)(nil).ActivateMember), customerId)
}

// CreateMember mocks base method.
func (m *MockmemberDb) CreateMember(c types.Customer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMember", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMember indicates an expected call of CreateMember.
func (mr *MockmemberDbMockRecorder) CreateMember(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMember", reflect.TypeOf((*MockmemberDb)(nil).CreateMember), c)
}

// DeactivateMember mocks base method.
func (m *MockmemberDb) DeactivateMember(customerId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateMember", customerId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateMember indicates an expected call of DeactivateMember.
func (mr *MockmemberDbMockRecorder) DeactivateMember(customerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateMember", reflect.TypeOf((*MockmemberDb)(nil).DeactivateMember), customerId)
}

// FindMemberByCustomerId mocks base method.
func (m *MockmemberDb) FindMemberByCustomerId(customerId string) (*types.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMemberByCustomerId", customerId)
	ret0, _ := ret[0].(*types.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMemberByCustomerId indicates an expected call of FindMemberByCustomerId.
func (mr *MockmemberDbMockRecorder) FindMemberByCustomerId(customerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMemberByCustomerId", reflect.TypeOf((*MockmemberDb)(nil).FindMemberByCustomerId), customerId)
}

// UpdateMemberAccess mocks base method.
func (m *MockmemberDb) UpdateMemberAccess(customerId, accessId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemberAccess", customerId, accessId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMemberAccess indicates an expected call of UpdateMemberAccess.
func (mr *MockmemberDbMockRecorder) UpdateMemberAccess(customerId, accessId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemberAccess", reflect.TypeOf((*MockmemberDb)(nil).UpdateMemberAccess), customerId, accessId)
}

// MockuaUpdater is a mock of uaUpdater interface.
type MockuaUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockuaUpdaterMockRecorder
	isgomock struct{}
}

// MockuaUpdaterMockRecorder is the mock recorder for MockuaUpdater.
type MockuaUpdaterMockRecorder struct {
	mock *MockuaUpdater
}

// NewMockuaUpdater creates a new mock instance.
func NewMockuaUpdater(ctrl *gomock.Controller) *MockuaUpdater {
	mock := &MockuaUpdater{ctrl: ctrl}
	mock.recorder = &MockuaUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuaUpdater) EXPECT() *MockuaUpdaterMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockuaUpdater) AddMember(arg0 types0.ComparableMember) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddMember indicates an expected call of AddMember.
func (mr *MockuaUpdaterMockRecorder) AddMember(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockuaUpdater)(nil).AddMember), arg0)
}

// DisableMember mocks base method.
func (m *MockuaUpdater) DisableMember(arg0 string, arg1 types0.ComparableMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableMember", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableMember indicates an expected call of DisableMember.
func (mr *MockuaUpdaterMockRecorder) DisableMember(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableMember", reflect.TypeOf((*MockuaUpdater)(nil).DisableMember), arg0, arg1)
}

// UpdateMember mocks base method.
func (m *MockuaUpdater) UpdateMember(arg0 string, arg1 types0.ComparableMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMember", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMember indicates an expected call of UpdateMember.
func (mr *MockuaUpdaterMockRecorder) UpdateMember(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMember", reflect.TypeOf((*MockuaUpdater)(nil).UpdateMember), arg0, arg1)
}
